{"timestamp": "2025-07-31T17:03:48.693245", "contexto": "Modo COMPLETO - Unidade TLS", "erro": "Nenhum registro encontrado após filtro de POIs", "tipo": "ValueError", "traceback": "Traceback (most recent call last):\n  File \"C:\\Users\\eusebioagj\\OneDrive\\Bot_C09\\main.py\", line 299, in processar_unidade_modo_completo\n    buffer_tratado = processor.processar_relatorio_c09(caminho_relatorio)\n                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\eusebioagj\\OneDrive\\Bot_C09\\core\\processor.py\", line 299, in processar_relatorio_c09\n    raise ValueError(\"Nenhum registro encontrado após filtro de POIs\")\nValueError: Nenhum registro encontrado após filtro de POIs\n"}
{"timestamp": "2025-07-31T17:06:50.663785", "contexto": "Modo COMPLETO - Unidade TLS", "erro": "Nenhum registro encontrado após filtro de POIs", "tipo": "ValueError", "traceback": "Traceback (most recent call last):\n  File \"C:\\Users\\eusebioagj\\OneDrive\\Bot_C09\\main.py\", line 299, in processar_unidade_modo_completo\n    buffer_tratado = processor.processar_relatorio_c09(caminho_relatorio)\n                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\eusebioagj\\OneDrive\\Bot_C09\\core\\processor.py\", line 299, in processar_relatorio_c09\n    raise ValueError(\"Nenhum registro encontrado após filtro de POIs\")\nValueError: Nenhum registro encontrado após filtro de POIs\n"}
