{"timestamp": "2025-07-31T17:03:48.693245", "contexto": "Modo COMPLETO - Unidade TLS", "erro": "Nenhum registro encontrado após filtro de POIs", "tipo": "ValueError", "traceback": "Traceback (most recent call last):\n  File \"C:\\Users\\eusebioagj\\OneDrive\\Bot_C09\\main.py\", line 299, in processar_unidade_modo_completo\n    buffer_tratado = processor.processar_relatorio_c09(caminho_relatorio)\n                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\eusebioagj\\OneDrive\\Bot_C09\\core\\processor.py\", line 299, in processar_relatorio_c09\n    raise ValueError(\"Nenhum registro encontrado após filtro de POIs\")\nValueError: Nenhum registro encontrado após filtro de POIs\n"}
{"timestamp": "2025-07-31T17:06:50.663785", "contexto": "Modo COMPLETO - Unidade TLS", "erro": "Nenhum registro encontrado após filtro de POIs", "tipo": "ValueError", "traceback": "Traceback (most recent call last):\n  File \"C:\\Users\\eusebioagj\\OneDrive\\Bot_C09\\main.py\", line 299, in processar_unidade_modo_completo\n    buffer_tratado = processor.processar_relatorio_c09(caminho_relatorio)\n                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\eusebioagj\\OneDrive\\Bot_C09\\core\\processor.py\", line 299, in processar_relatorio_c09\n    raise ValueError(\"Nenhum registro encontrado após filtro de POIs\")\nValueError: Nenhum registro encontrado após filtro de POIs\n"}
{"timestamp": "2025-07-31T18:45:49.867413", "contexto": "Modo COMPLETO - Unidade RRP", "erro": "Message: no such element: Unable to locate element: {\"method\":\"xpath\",\"selector\":\"//a[contains(text(), 'C09')]\"}\n  (Session info: chrome=136.0.7103.114); For documentation on this error, please visit: https://www.selenium.dev/documentation/webdriver/troubleshooting/errors#nosuchelementexception\nStacktrace:\n\tGetHandleVerifier [0x00007FF74E7CCF65+75717]\n\tGetHandleVerifier [0x00007FF74E7CCFC0+75808]\n\t(No symbol) [0x00007FF74E598F9A]\n\t(No symbol) [0x00007FF74E5EF4C6]\n\t(No symbol) [0x00007FF74E5EF77C]\n\t(No symbol) [0x00007FF74E642577]\n\t(No symbol) [0x00007FF74E6173BF]\n\t(No symbol) [0x00007FF74E63F39C]\n\t(No symbol) [0x00007FF74E617153]\n\t(No symbol) [0x00007FF74E5E0421]\n\t(No symbol) [0x00007FF74E5E11B3]\n\tGetHandleVerifier [0x00007FF74EACD74D+3223469]\n\tGetHandleVerifier [0x00007FF74EAC7CF2+3200338]\n\tGetHandleVerifier [0x00007FF74EAE5B23+3322755]\n\tGetHandleVerifier [0x00007FF74E7E6A3A+180890]\n\tGetHandleVerifier [0x00007FF74E7EE13F+211359]\n\tGetHandleVerifier [0x00007FF74E7D52B4+109332]\n\tGetHandleVerifier [0x00007FF74E7D5462+109762]\n\tGetHandleVerifier [0x00007FF74E7BBA79+4825]\n\tBaseThreadInitThunk [0x00007FFA665F259D+29]\n\tRtlUserThreadStart [0x00007FFA6690AF78+40]\n", "tipo": "NoSuchElementException", "traceback": "Traceback (most recent call last):\n  File \"C:\\Users\\eusebioagj\\OneDrive\\Bot_C09\\main.py\", line 294, in processar_unidade_modo_completo\n    caminho_relatorio = self.scraper.baixar_relatorio_c09(\n                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\eusebioagj\\OneDrive\\Bot_C09\\core\\scraper.py\", line 403, in baixar_relatorio_c09\n    self._navegar_para_c09(driver, wait)\n  File \"C:\\Users\\eusebioagj\\OneDrive\\Bot_C09\\core\\scraper.py\", line 220, in _navegar_para_c09\n    driver.find_element(By.XPATH, \"//a[contains(text(), 'C09')]\").click()\n    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\eusebioagj\\AppData\\Local\\Programs\\Python\\Python311\\Lib\\site-packages\\selenium\\webdriver\\remote\\webdriver.py\", line 922, in find_element\n    return self.execute(Command.FIND_ELEMENT, {\"using\": by, \"value\": value})[\"value\"]\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\eusebioagj\\AppData\\Local\\Programs\\Python\\Python311\\Lib\\site-packages\\selenium\\webdriver\\remote\\webdriver.py\", line 454, in execute\n    self.error_handler.check_response(response)\n  File \"C:\\Users\\eusebioagj\\AppData\\Local\\Programs\\Python\\Python311\\Lib\\site-packages\\selenium\\webdriver\\remote\\errorhandler.py\", line 232, in check_response\n    raise exception_class(message, screen, stacktrace)\nselenium.common.exceptions.NoSuchElementException: Message: no such element: Unable to locate element: {\"method\":\"xpath\",\"selector\":\"//a[contains(text(), 'C09')]\"}\n  (Session info: chrome=136.0.7103.114); For documentation on this error, please visit: https://www.selenium.dev/documentation/webdriver/troubleshooting/errors#nosuchelementexception\nStacktrace:\n\tGetHandleVerifier [0x00007FF74E7CCF65+75717]\n\tGetHandleVerifier [0x00007FF74E7CCFC0+75808]\n\t(No symbol) [0x00007FF74E598F9A]\n\t(No symbol) [0x00007FF74E5EF4C6]\n\t(No symbol) [0x00007FF74E5EF77C]\n\t(No symbol) [0x00007FF74E642577]\n\t(No symbol) [0x00007FF74E6173BF]\n\t(No symbol) [0x00007FF74E63F39C]\n\t(No symbol) [0x00007FF74E617153]\n\t(No symbol) [0x00007FF74E5E0421]\n\t(No symbol) [0x00007FF74E5E11B3]\n\tGetHandleVerifier [0x00007FF74EACD74D+3223469]\n\tGetHandleVerifier [0x00007FF74EAC7CF2+3200338]\n\tGetHandleVerifier [0x00007FF74EAE5B23+3322755]\n\tGetHandleVerifier [0x00007FF74E7E6A3A+180890]\n\tGetHandleVerifier [0x00007FF74E7EE13F+211359]\n\tGetHandleVerifier [0x00007FF74E7D52B4+109332]\n\tGetHandleVerifier [0x00007FF74E7D5462+109762]\n\tGetHandleVerifier [0x00007FF74E7BBA79+4825]\n\tBaseThreadInitThunk [0x00007FFA665F259D+29]\n\tRtlUserThreadStart [0x00007FFA6690AF78+40]\n\n"}
{"timestamp": "2025-07-31T18:48:54.849057", "contexto": "Modo COMPLETO - Unidade RRP", "erro": "Message: tab crashed\n  (Session info: chrome=136.0.7103.114)\nStacktrace:\n\tGetHandleVerifier [0x00007FF74E7CCF65+75717]\n\tGetHandleVerifier [0x00007FF74E7CCFC0+75808]\n\t(No symbol) [0x00007FF74E598DCC]\n\t(No symbol) [0x00007FF74E58617B]\n\t(No symbol) [0x00007FF74E583E8A]\n\t(No symbol) [0x00007FF74E58483F]\n\t(No symbol) [0x00007FF74E5933AE]\n\t(No symbol) [0x00007FF74E5A97E1]\n\t(No symbol) [0x00007FF74E5B091A]\n\t(No symbol) [0x00007FF74E584FAD]\n\t(No symbol) [0x00007FF74E5A8FD1]\n\t(No symbol) [0x00007FF74E63F276]\n\t(No symbol) [0x00007FF74E617153]\n\t(No symbol) [0x00007FF74E5E0421]\n\t(No symbol) [0x00007FF74E5E11B3]\n\tGetHandleVerifier [0x00007FF74EACD74D+3223469]\n\tGetHandleVerifier [0x00007FF74EAC7CF2+3200338]\n\tGetHandleVerifier [0x00007FF74EAE5B23+3322755]\n\tGetHandleVerifier [0x00007FF74E7E6A3A+180890]\n\tGetHandleVerifier [0x00007FF74E7EE13F+211359]\n\tGetHandleVerifier [0x00007FF74E7D52B4+109332]\n\tGetHandleVerifier [0x00007FF74E7D5462+109762]\n\tGetHandleVerifier [0x00007FF74E7BBA79+4825]\n\tBaseThreadInitThunk [0x00007FFA665F259D+29]\n\tRtlUserThreadStart [0x00007FFA6690AF78+40]\n", "tipo": "WebDriverException", "traceback": "Traceback (most recent call last):\n  File \"C:\\Users\\eusebioagj\\OneDrive\\Bot_C09\\main.py\", line 294, in processar_unidade_modo_completo\n    caminho_relatorio = self.scraper.baixar_relatorio_c09(\n                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\eusebioagj\\OneDrive\\Bot_C09\\core\\scraper.py\", line 415, in baixar_relatorio_c09\n    self._aguardar_e_baixar(driver, wait)\n  File \"C:\\Users\\eusebioagj\\OneDrive\\Bot_C09\\core\\scraper.py\", line 329, in _aguardar_e_baixar\n    status = driver.find_element(\n             ^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\eusebioagj\\AppData\\Local\\Programs\\Python\\Python311\\Lib\\site-packages\\selenium\\webdriver\\remote\\webdriver.py\", line 922, in find_element\n    return self.execute(Command.FIND_ELEMENT, {\"using\": by, \"value\": value})[\"value\"]\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\eusebioagj\\AppData\\Local\\Programs\\Python\\Python311\\Lib\\site-packages\\selenium\\webdriver\\remote\\webdriver.py\", line 454, in execute\n    self.error_handler.check_response(response)\n  File \"C:\\Users\\eusebioagj\\AppData\\Local\\Programs\\Python\\Python311\\Lib\\site-packages\\selenium\\webdriver\\remote\\errorhandler.py\", line 232, in check_response\n    raise exception_class(message, screen, stacktrace)\nselenium.common.exceptions.WebDriverException: Message: tab crashed\n  (Session info: chrome=136.0.7103.114)\nStacktrace:\n\tGetHandleVerifier [0x00007FF74E7CCF65+75717]\n\tGetHandleVerifier [0x00007FF74E7CCFC0+75808]\n\t(No symbol) [0x00007FF74E598DCC]\n\t(No symbol) [0x00007FF74E58617B]\n\t(No symbol) [0x00007FF74E583E8A]\n\t(No symbol) [0x00007FF74E58483F]\n\t(No symbol) [0x00007FF74E5933AE]\n\t(No symbol) [0x00007FF74E5A97E1]\n\t(No symbol) [0x00007FF74E5B091A]\n\t(No symbol) [0x00007FF74E584FAD]\n\t(No symbol) [0x00007FF74E5A8FD1]\n\t(No symbol) [0x00007FF74E63F276]\n\t(No symbol) [0x00007FF74E617153]\n\t(No symbol) [0x00007FF74E5E0421]\n\t(No symbol) [0x00007FF74E5E11B3]\n\tGetHandleVerifier [0x00007FF74EACD74D+3223469]\n\tGetHandleVerifier [0x00007FF74EAC7CF2+3200338]\n\tGetHandleVerifier [0x00007FF74EAE5B23+3322755]\n\tGetHandleVerifier [0x00007FF74E7E6A3A+180890]\n\tGetHandleVerifier [0x00007FF74E7EE13F+211359]\n\tGetHandleVerifier [0x00007FF74E7D52B4+109332]\n\tGetHandleVerifier [0x00007FF74E7D5462+109762]\n\tGetHandleVerifier [0x00007FF74E7BBA79+4825]\n\tBaseThreadInitThunk [0x00007FFA665F259D+29]\n\tRtlUserThreadStart [0x00007FFA6690AF78+40]\n\n"}
{"timestamp": "2025-07-31T18:51:50.447346", "contexto": "Modo COMPLETO - Unidade TLS", "erro": "Message: Can not connect to the Service .\\chromedriver-win64\\chromedriver.exe\n", "tipo": "WebDriverException", "traceback": "Traceback (most recent call last):\n  File \"C:\\Users\\eusebioagj\\OneDrive\\Bot_C09\\main.py\", line 294, in processar_unidade_modo_completo\n    caminho_relatorio = self.scraper.baixar_relatorio_c09(\n                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\eusebioagj\\OneDrive\\Bot_C09\\core\\scraper.py\", line 396, in baixar_relatorio_c09\n    driver = self._create_webdriver()\n             ^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\eusebioagj\\OneDrive\\Bot_C09\\core\\scraper.py\", line 166, in _create_webdriver\n    driver = webdriver.Chrome(service=service, options=options)\n             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\eusebioagj\\AppData\\Local\\Programs\\Python\\Python311\\Lib\\site-packages\\selenium\\webdriver\\chrome\\webdriver.py\", line 47, in __init__\n    super().__init__(\n  File \"C:\\Users\\eusebioagj\\AppData\\Local\\Programs\\Python\\Python311\\Lib\\site-packages\\selenium\\webdriver\\chromium\\webdriver.py\", line 58, in __init__\n    self.service.start()\n  File \"C:\\Users\\eusebioagj\\AppData\\Local\\Programs\\Python\\Python311\\Lib\\site-packages\\selenium\\webdriver\\common\\service.py\", line 115, in start\n    raise WebDriverException(f\"Can not connect to the Service {self._path}\")\nselenium.common.exceptions.WebDriverException: Message: Can not connect to the Service .\\chromedriver-win64\\chromedriver.exe\n\n"}
{"timestamp": "2025-07-31T18:52:27.222472", "contexto": "Modo COMPLETO - Unidade RRP", "erro": "Message: Can not connect to the Service .\\chromedriver-win64\\chromedriver.exe\n", "tipo": "WebDriverException", "traceback": "Traceback (most recent call last):\n  File \"C:\\Users\\eusebioagj\\OneDrive\\Bot_C09\\main.py\", line 294, in processar_unidade_modo_completo\n    caminho_relatorio = self.scraper.baixar_relatorio_c09(\n                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\eusebioagj\\OneDrive\\Bot_C09\\core\\scraper.py\", line 396, in baixar_relatorio_c09\n    driver = self._create_webdriver()\n             ^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\eusebioagj\\OneDrive\\Bot_C09\\core\\scraper.py\", line 166, in _create_webdriver\n    driver = webdriver.Chrome(service=service, options=options)\n             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\eusebioagj\\AppData\\Local\\Programs\\Python\\Python311\\Lib\\site-packages\\selenium\\webdriver\\chrome\\webdriver.py\", line 47, in __init__\n    super().__init__(\n  File \"C:\\Users\\eusebioagj\\AppData\\Local\\Programs\\Python\\Python311\\Lib\\site-packages\\selenium\\webdriver\\chromium\\webdriver.py\", line 58, in __init__\n    self.service.start()\n  File \"C:\\Users\\eusebioagj\\AppData\\Local\\Programs\\Python\\Python311\\Lib\\site-packages\\selenium\\webdriver\\common\\service.py\", line 115, in start\n    raise WebDriverException(f\"Can not connect to the Service {self._path}\")\nselenium.common.exceptions.WebDriverException: Message: Can not connect to the Service .\\chromedriver-win64\\chromedriver.exe\n\n"}
{"timestamp": "2025-07-31T20:25:33.480520", "contexto": "Modo COMPLETO - Unidade TLS", "erro": "Message: no such element: Unable to locate element: {\"method\":\"xpath\",\"selector\":\"//a[contains(text(), 'C09')]\"}\n  (Session info: chrome=136.0.7103.114); For documentation on this error, please visit: https://www.selenium.dev/documentation/webdriver/troubleshooting/errors#nosuchelementexception\nStacktrace:\n\tGetHandleVerifier [0x00007FF79E97CF65+75717]\n\tGetHandleVerifier [0x00007FF79E97CFC0+75808]\n\t(No symbol) [0x00007FF79E748F9A]\n\t(No symbol) [0x00007FF79E79F4C6]\n\t(No symbol) [0x00007FF79E79F77C]\n\t(No symbol) [0x00007FF79E7F2577]\n\t(No symbol) [0x00007FF79E7C73BF]\n\t(No symbol) [0x00007FF79E7EF39C]\n\t(No symbol) [0x00007FF79E7C7153]\n\t(No symbol) [0x00007FF79E790421]\n\t(No symbol) [0x00007FF79E7911B3]\n\tGetHandleVerifier [0x00007FF79EC7D74D+3223469]\n\tGetHandleVerifier [0x00007FF79EC77CF2+3200338]\n\tGetHandleVerifier [0x00007FF79EC95B23+3322755]\n\tGetHandleVerifier [0x00007FF79E996A3A+180890]\n\tGetHandleVerifier [0x00007FF79E99E13F+211359]\n\tGetHandleVerifier [0x00007FF79E9852B4+109332]\n\tGetHandleVerifier [0x00007FF79E985462+109762]\n\tGetHandleVerifier [0x00007FF79E96BA79+4825]\n\tBaseThreadInitThunk [0x00007FFD1B55259D+29]\n\tRtlUserThreadStart [0x00007FFD1B86AF78+40]\n", "tipo": "NoSuchElementException", "traceback": "Traceback (most recent call last):\n  File \"C:\\Users\\eusebioagj\\OneDrive\\Bot_C09\\main.py\", line 294, in processar_unidade_modo_completo\n    caminho_relatorio = self.scraper.baixar_relatorio_c09(\n                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\eusebioagj\\OneDrive\\Bot_C09\\core\\scraper.py\", line 403, in baixar_relatorio_c09\n    self._navegar_para_c09(driver, wait)\n  File \"C:\\Users\\eusebioagj\\OneDrive\\Bot_C09\\core\\scraper.py\", line 220, in _navegar_para_c09\n    driver.find_element(By.XPATH, \"//a[contains(text(), 'C09')]\").click()\n    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\eusebioagj\\AppData\\Local\\Programs\\Python\\Python311\\Lib\\site-packages\\selenium\\webdriver\\remote\\webdriver.py\", line 922, in find_element\n    return self.execute(Command.FIND_ELEMENT, {\"using\": by, \"value\": value})[\"value\"]\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\eusebioagj\\AppData\\Local\\Programs\\Python\\Python311\\Lib\\site-packages\\selenium\\webdriver\\remote\\webdriver.py\", line 454, in execute\n    self.error_handler.check_response(response)\n  File \"C:\\Users\\eusebioagj\\AppData\\Local\\Programs\\Python\\Python311\\Lib\\site-packages\\selenium\\webdriver\\remote\\errorhandler.py\", line 232, in check_response\n    raise exception_class(message, screen, stacktrace)\nselenium.common.exceptions.NoSuchElementException: Message: no such element: Unable to locate element: {\"method\":\"xpath\",\"selector\":\"//a[contains(text(), 'C09')]\"}\n  (Session info: chrome=136.0.7103.114); For documentation on this error, please visit: https://www.selenium.dev/documentation/webdriver/troubleshooting/errors#nosuchelementexception\nStacktrace:\n\tGetHandleVerifier [0x00007FF79E97CF65+75717]\n\tGetHandleVerifier [0x00007FF79E97CFC0+75808]\n\t(No symbol) [0x00007FF79E748F9A]\n\t(No symbol) [0x00007FF79E79F4C6]\n\t(No symbol) [0x00007FF79E79F77C]\n\t(No symbol) [0x00007FF79E7F2577]\n\t(No symbol) [0x00007FF79E7C73BF]\n\t(No symbol) [0x00007FF79E7EF39C]\n\t(No symbol) [0x00007FF79E7C7153]\n\t(No symbol) [0x00007FF79E790421]\n\t(No symbol) [0x00007FF79E7911B3]\n\tGetHandleVerifier [0x00007FF79EC7D74D+3223469]\n\tGetHandleVerifier [0x00007FF79EC77CF2+3200338]\n\tGetHandleVerifier [0x00007FF79EC95B23+3322755]\n\tGetHandleVerifier [0x00007FF79E996A3A+180890]\n\tGetHandleVerifier [0x00007FF79E99E13F+211359]\n\tGetHandleVerifier [0x00007FF79E9852B4+109332]\n\tGetHandleVerifier [0x00007FF79E985462+109762]\n\tGetHandleVerifier [0x00007FF79E96BA79+4825]\n\tBaseThreadInitThunk [0x00007FFD1B55259D+29]\n\tRtlUserThreadStart [0x00007FFD1B86AF78+40]\n\n"}
